### ISSUE TITLE
what problem it is..

### ISSUE THREAD

**Issue by UGlengmo** [ChrisK91/CWSRestart#10]
![image](https://github.com/ChrisK91/CWSRestart/assets/82253809/9980abc7-1371-4684-886f-079d23180b3b)

**Comment by UGlengmo** [comment]
![image](https://github.com/ChrisK91/CWSRestart/assets/82253809/c5a72127-01d6-4ee6-a7e8-bc829a4cb745)

**Comment by ChrisK91** [comment]
Unfortunately the software itself is quite old now, and hasnt been updated in ages. It might be, that the data packages exchanged between the server and client have been updated, and CWSRestart is unable to read them. You could also try to see, if one of the forks has been updated and maintained to work with newer versions.
